# Generated by Django 3.2.12 on 2022-03-23 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=30)),
                ('artist_firstname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_start_date', models.DateTimeField(verbose_name='date de début')),
                ('event_end_date', models.DateTimeField(verbose_name='date de fin')),
                ('book', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='date de début')),
                ('end_date', models.DateTimeField(verbose_name='date de fin')),
            ],
        ),
        migrations.CreateModel(
            name='TyOfShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_showroom_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_event_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WhoIsHere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_is_here_name', models.CharField(max_length=30)),
                ('have', models.ManyToManyField(to='reservation.Artists')),
            ],
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showroom_name', models.CharField(max_length=30)),
                ('showroom_places', models.IntegerField(default=0)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.events')),
                ('tyofshowroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.tyofshowroom')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='perform',
            field=models.ManyToManyField(to='reservation.WhoIsHere'),
        ),
        migrations.AddField(
            model_name='events',
            name='prepare',
            field=models.ManyToManyField(to='reservation.Schedule'),
        ),
        migrations.AddField(
            model_name='events',
            name='type_of_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.typeofevents'),
        ),
    ]
