# Generated by Django 3.2.12 on 2022-03-23 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0004_alter_events_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='book',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
