# Generated by Django 3.2.12 on 2022-03-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_events_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='tyofshowroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.tyofshowroom'),
        ),
    ]
