# Generated by Django 3.2.12 on 2022-03-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_alter_events_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroom',
            name='events',
        ),
        migrations.AddField(
            model_name='showroom',
            name='events',
            field=models.ManyToManyField(blank=True, to='reservation.Events'),
        ),
    ]
