# Generated by Django 3.2.12 on 2022-03-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20220325_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showroom',
            old_name='events',
            new_name='take',
        ),
    ]
