# Generated by Django 3.2.12 on 2022-03-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_rename_events_showroom_take'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroom',
            name='take',
        ),
        migrations.AddField(
            model_name='events',
            name='take',
            field=models.ManyToManyField(blank=True, to='reservation.Showroom'),
        ),
    ]
