# Generated by Django 3.2.12 on 2022-03-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20220325_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='sold_places',
            field=models.IntegerField(default=0),
        ),
    ]
